export const FIELD_CHANGE_VALUE = 'FIELD_CHANGE_VALUE';
export const INCREMENT_VALUE = 'INCREMENT_VALUE';
export const DECREMENT_VALUE = 'DECREMENT_VALUE';
export const ADD_ITEM_VALUE = 'ADD_ITEM_VALUE';
export const REMOVE_ITEM_VALUE = 'REMOVE_ITEM_VALUE';
export const ADD_ITEMS_VALUE = 'ADD_ITEMS_VALUE';
export const REMOVE_ITEMS_VALUE = 'REMOVE_ITEMS_VALUE';
